# Generated by Django 4.2.17 on 2024-12-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
