# Generated by Django 4.2.17 on 2024-12-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('classificacao_etaria', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_convite', models.DateField()),
                ('mensagem', models.CharField(max_length=250)),
                ('jogador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_jogador1', to='app.perfil_jogador')),
                ('jogador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_jogador2', to='app.perfil_jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo')),
            ],
        ),
    ]
