# Generated by Django 4.2.17 on 2024-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_jogador',
            name='apelido',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_jogador',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_jogador',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil_jogador',
            name='senha',
            field=models.CharField(max_length=30),
        ),
    ]
