# Generated by Django 4.2.17 on 2024-12-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_perfil_jogador_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_jogador',
            name='teste',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
