# Generated by Django 4.2.17 on 2024-12-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_perfil_jogador_table'),
    ]

    operations = []
